sudo: required

language : generic

services :
  - docker

before_install:
  - echo "DockerFile 이미지 생성"
  - docker build -t kangchansong/mbti_zip_front -f Dockerfile.dev .

script:
  - docker run -e CI=true kangchansong/mbti_zip_front npm run test -- --passWithNoTests

before_deploy:
  - zip -r mbti_zip_front *
  - mkdir -p deploy
  - mv mbti_zip_front.zip deploy/mbti_zip_front.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    key: mbti_zip_front.zip
    bundle-type: zip
    application: mbti-zip
    deployment-group: mbti-zip-group
    region: ap-northeast-2
    wait-until-reploy: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'thdrkdcks@naver.com'