
os:
  - linux

language : node_js

node_js:
  - 'stable'

sudo: required

branches:
  only:
    - master 

cache:
  directories:
    - node_modules

before_install:
  - yarn build

before_deploy:
  - mkdir -p deploy
  - zip -r build *
  - echo "============================ BUILDED ========================="
  - ll
  - echo "================================================================"
  - mv build/build.zip deploy/build.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    key: build.zip
    bundle-type: zip
    application: mbti-zip
    deployment-group: mbti-zip-front
    region: ap-northeast-2
    wait-until-deploy: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'thdrkdcks@naver.com'