sudo: required

language : generic


before_deploy:
  - mkdir -p before-deploy
  - cp * before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/mbti_zip.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    key: mbti_zip_front.zip
    bundle-type: zip
    application: mbti-zip-front
    deployment-group: mbti-zip-front
    region: ap-northeast-2
    wait-until-deploy: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'thdrkdcks@naver.com'