
language : node_js

node_js:
  - "10.14"

branches:
  only:
    - master 

before_install:
  - npm install -g yarn

before_deploy:
  - rm -rf node_modules
  - zip -r mbti_zip_front *
  - mkdir -p deploy
  - mv mbti_zip_front.zip deploy/mbti_zip_front.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy
    wait-until-deploy: true
    on:
      repo: kangchansong/mbti_zip_front
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: mbti-zip-build
    key: mbti_zip_front.zip
    bundle-type: zip
    application: mbti-zip
    deployment-group: mbti-zip-front
    region: ap-northeast-2
    wait-until-deploy: true
    on:
      repo: kangchansong/mbti_zip_front
      branch: master


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'thdrkdcks@naver.com'