version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/mbti_zip_front
    overwrite: yes

permissions:
  - object: /
    patterns: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180
