FROM node:alpine

WORKDIR '/usr/src/app'

COPY package.json ./

RUN npm install

COPY ./ ./

# ENV CHOKIDAR_USEPOLLING=true

RUN npm run build

#nginx base image
FROM nginx
EXPOSE 80

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

CMD ["npm", "run", "start"]